// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UchetNZP.Infrastructure.Data;

#nullable disable

namespace UchetNZP.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015054130_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UchetNZP.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NormHours")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "OpNumber")
                        .IsUnique();

                    b.ToTable("PartRoutes", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OpNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "SectionId", "OpNumber")
                        .IsUnique();

                    b.ToTable("WipBalances", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "SectionId", "LaunchDate");

                    b.ToTable("WipLaunches", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunchOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Hours")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PartRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WipLaunchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("PartRouteId");

                    b.HasIndex("SectionId");

                    b.HasIndex("WipLaunchId", "OpNumber")
                        .IsUnique();

                    b.ToTable("WipLaunchOperations", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "SectionId", "OpNumber", "ReceiptDate");

                    b.ToTable("WipReceipts", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Operation", "Operation")
                        .WithMany("PartRoutes")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("Routes")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("PartRoutes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalance", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipBalances")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipBalances")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipLaunches")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipLaunches")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunchOperation", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Operation", "Operation")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.PartRoute", "PartRoute")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("PartRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLaunch", "WipLaunch")
                        .WithMany("Operations")
                        .HasForeignKey("WipLaunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("PartRoute");

                    b.Navigation("Section");

                    b.Navigation("WipLaunch");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipReceipt", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipReceipts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipReceipts")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Operation", b =>
                {
                    b.Navigation("PartRoutes");

                    b.Navigation("WipLaunchOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Part", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("WipBalances");

                    b.Navigation("WipLaunches");

                    b.Navigation("WipReceipts");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.Navigation("WipLaunchOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Section", b =>
                {
                    b.Navigation("PartRoutes");

                    b.Navigation("WipBalances");

                    b.Navigation("WipLaunchOperations");

                    b.Navigation("WipLaunches");

                    b.Navigation("WipReceipts");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
