// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UchetNZP.Infrastructure.Data;

#nullable disable

namespace UchetNZP.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306045545_AddWipLabelCycleYear")]
    partial class AddWipLabelCycleYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UchetNZP.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Skipped")
                        .HasColumnType("integer");

                    b.Property<int>("Succeeded")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ImportJobs", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.ImportJobItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("RowIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId", "RowIndex")
                        .IsUnique();

                    b.ToTable("ImportJobItems", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.LabelMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InputLabelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutputLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InputLabelId");

                    b.HasIndex("OutputLabelId");

                    b.HasIndex("InputLabelId", "OutputLabelId")
                        .IsUnique();

                    b.ToTable("LabelMerges", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.LabelNumberCounter", b =>
                {
                    b.Property<string>("RootNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("NextSuffix")
                        .HasColumnType("integer");

                    b.HasKey("RootNumber");

                    b.ToTable("LabelNumberCounters", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Operations", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Parts", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("NormHours")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "OpNumber")
                        .IsUnique();

                    b.ToTable("PartRoutes", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.ReceiptAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NewBalance")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<bool>("NewLabelAssigned")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("NewLabelId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NewQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PreviousBalance")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<bool>("PreviousLabelAssigned")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PreviousLabelId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PreviousQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ReceiptAudits", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FromBalanceAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FromBalanceBefore")
                        .HasColumnType("numeric");

                    b.Property<int>("FromOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromSectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWarehouseTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("LabelNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("LabelQuantityAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LabelQuantityBefore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ResidualLabelNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("ResidualLabelQuantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ResidualWipLabelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScrapComment")
                        .HasColumnType("text");

                    b.Property<decimal>("ScrapQuantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("ScrapType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToBalanceAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ToBalanceBefore")
                        .HasColumnType("numeric");

                    b.Property<int>("ToOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WipLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TransferAudits");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferAuditOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsWarehouse")
                        .HasColumnType("boolean");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartRouteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransferAuditId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransferAuditId");

                    b.ToTable("TransferAuditOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferLabelUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedToLabelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromLabelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("RemainingBefore")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("ScrapQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedToLabelId");

                    b.HasIndex("FromLabelId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferLabelUsages", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransferLabelUsages_Consumption_WithinRemaining", "(\"Qty\" + \"ScrapQty\") <= \"RemainingBefore\"");

                            t.HasCheckConstraint("CK_TransferLabelUsages_Qty_NonNegative", "\"Qty\" >= 0");

                            t.HasCheckConstraint("CK_TransferLabelUsages_RemainingBefore_NonNegative", "\"RemainingBefore\" >= 0");

                            t.HasCheckConstraint("CK_TransferLabelUsages_ScrapQty_NonNegative", "\"ScrapQty\" >= 0");
                        });
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WarehouseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("TransferId")
                        .IsUnique();

                    b.ToTable("WarehouseItems", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WarehouseLabelItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WipLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseItemId");

                    b.HasIndex("WipLabelId");

                    b.ToTable("WarehouseLabelItems", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "SectionId", "OpNumber")
                        .IsUnique();

                    b.ToTable("WipBalances", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalanceAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Delta")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("NewQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PreviousQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WipBalanceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("SectionId");

                    b.HasIndex("WipBalanceId");

                    b.ToTable("WipBalanceAdjustments", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CurrentSectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CycleYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LabelDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("ParentLabelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("RootLabelId")
                        .HasColumnType("uuid");

                    b.Property<string>("RootNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasDefaultValueSql("'\\x'::bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Suffix")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("RootLabelId");

                    b.HasIndex("Number", "CycleYear")
                        .IsUnique();

                    b.HasIndex("RootNumber", "Suffix", "CycleYear")
                        .IsUnique();

                    b.HasIndex("Status", "CurrentSectionId", "CurrentOpNumber");

                    b.ToTable("WipLabels", null, t =>
                        {
                            t.HasCheckConstraint("CK_WipLabels_Quantity_Positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_WipLabels_Remaining_NonNegative", "\"RemainingQuantity\" >= 0");

                            t.HasCheckConstraint("CK_WipLabels_Remaining_NotGreaterThanQuantity", "\"RemainingQuantity\" <= \"Quantity\"");
                        });
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLabelLedger", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("FromLabelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FromSectionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid?>("RefEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefEntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("ScrapQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid?>("ToLabelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ToOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ToSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("EventTime");

                    b.HasIndex("FromLabelId");

                    b.HasIndex("ToLabelId");

                    b.HasIndex("TransactionId");

                    b.ToTable("WipLabelLedger", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromOpNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SumHoursToFinish")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("PartId", "SectionId", "LaunchDate");

                    b.ToTable("WipLaunches", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunchOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Hours")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("NormHours")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartRouteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WipLaunchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("PartRouteId");

                    b.HasIndex("SectionId");

                    b.HasIndex("WipLaunchId", "OpNumber")
                        .IsUnique();

                    b.ToTable("WipLaunchOperations", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WipLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("WipLabelId")
                        .IsUnique();

                    b.HasIndex("PartId", "SectionId", "OpNumber", "ReceiptDate");

                    b.ToTable("WipReceipts", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipScrap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScrapType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("TransferId")
                        .IsUnique();

                    b.HasIndex("PartId", "OpNumber");

                    b.ToTable("WipScraps", (string)null);
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("FromSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("ToOpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("ToSectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WipLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("WipLabelId");

                    b.ToTable("WipTransfers");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipTransferOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OpNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PartRouteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WipTransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("PartRouteId");

                    b.HasIndex("SectionId");

                    b.HasIndex("WipTransferId");

                    b.ToTable("WipTransferOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.ImportJobItem", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.ImportJob", "ImportJob")
                        .WithMany("Items")
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportJob");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.LabelMerge", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "InputLabel")
                        .WithMany("MergeOutputs")
                        .HasForeignKey("InputLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "OutputLabel")
                        .WithMany("MergeInputs")
                        .HasForeignKey("OutputLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InputLabel");

                    b.Navigation("OutputLabel");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Operation", "Operation")
                        .WithMany("PartRoutes")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("Routes")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("PartRoutes")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferAuditOperation", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.TransferAudit", "TransferAudit")
                        .WithMany("Operations")
                        .HasForeignKey("TransferAuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransferAudit");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferLabelUsage", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "CreatedToLabel")
                        .WithMany("TransferUsagesAsCreated")
                        .HasForeignKey("CreatedToLabelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "FromLabel")
                        .WithMany("TransferUsagesAsSource")
                        .HasForeignKey("FromLabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipTransfer", "Transfer")
                        .WithMany("LabelUsages")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedToLabel");

                    b.Navigation("FromLabel");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WarehouseItem", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipTransfer", "Transfer")
                        .WithOne("WarehouseItem")
                        .HasForeignKey("UchetNZP.Domain.Entities.WarehouseItem", "TransferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WarehouseLabelItem", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.WarehouseItem", "WarehouseItem")
                        .WithMany("WarehouseLabelItems")
                        .HasForeignKey("WarehouseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "WipLabel")
                        .WithMany("WarehouseLabelItems")
                        .HasForeignKey("WipLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WarehouseItem");

                    b.Navigation("WipLabel");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalance", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipBalances")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipBalances")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipBalanceAdjustment", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipBalance", "Balance")
                        .WithMany()
                        .HasForeignKey("WipBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLabel", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipLabels")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipLaunches")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipLaunches")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunchOperation", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Operation", "Operation")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.PartRoute", "PartRoute")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("PartRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipLaunchOperations")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLaunch", "WipLaunch")
                        .WithMany("Operations")
                        .HasForeignKey("WipLaunchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("PartRoute");

                    b.Navigation("Section");

                    b.Navigation("WipLaunch");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipReceipt", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipReceipts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipReceipts")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "WipLabel")
                        .WithOne("WipReceipt")
                        .HasForeignKey("UchetNZP.Domain.Entities.WipReceipt", "WipLabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("Section");

                    b.Navigation("WipLabel");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipScrap", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany("WipScraps")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany("WipScraps")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipTransfer", "Transfer")
                        .WithOne("Scrap")
                        .HasForeignKey("UchetNZP.Domain.Entities.WipScrap", "TransferId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("Section");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipTransfer", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipLabel", "WipLabel")
                        .WithMany("Transfers")
                        .HasForeignKey("WipLabelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("WipLabel");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipTransferOperation", b =>
                {
                    b.HasOne("UchetNZP.Domain.Entities.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.PartRoute", "PartRoute")
                        .WithMany()
                        .HasForeignKey("PartRouteId");

                    b.HasOne("UchetNZP.Domain.Entities.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UchetNZP.Domain.Entities.WipTransfer", "WipTransfer")
                        .WithMany("Operations")
                        .HasForeignKey("WipTransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("PartRoute");

                    b.Navigation("Section");

                    b.Navigation("WipTransfer");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.ImportJob", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Operation", b =>
                {
                    b.Navigation("PartRoutes");

                    b.Navigation("WipLaunchOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Part", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("WarehouseItems");

                    b.Navigation("WipBalances");

                    b.Navigation("WipLabels");

                    b.Navigation("WipLaunches");

                    b.Navigation("WipReceipts");

                    b.Navigation("WipScraps");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.PartRoute", b =>
                {
                    b.Navigation("WipLaunchOperations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.Section", b =>
                {
                    b.Navigation("PartRoutes");

                    b.Navigation("WipBalances");

                    b.Navigation("WipLaunchOperations");

                    b.Navigation("WipLaunches");

                    b.Navigation("WipReceipts");

                    b.Navigation("WipScraps");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.TransferAudit", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WarehouseItem", b =>
                {
                    b.Navigation("WarehouseLabelItems");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLabel", b =>
                {
                    b.Navigation("MergeInputs");

                    b.Navigation("MergeOutputs");

                    b.Navigation("TransferUsagesAsCreated");

                    b.Navigation("TransferUsagesAsSource");

                    b.Navigation("Transfers");

                    b.Navigation("WarehouseLabelItems");

                    b.Navigation("WipReceipt");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipLaunch", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("UchetNZP.Domain.Entities.WipTransfer", b =>
                {
                    b.Navigation("LabelUsages");

                    b.Navigation("Operations");

                    b.Navigation("Scrap");

                    b.Navigation("WarehouseItem");
                });
#pragma warning restore 612, 618
        }
    }
}
