// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using UchetNZP.Infrastructure.Data;

#nullable disable

namespace UchetNZP.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260504141500_AddMetalReceiptOriginalDocumentAndAverageSize")]
partial class AddMetalReceiptOriginalDocumentAndAverageSize
{
}
